language: java
#jdk:
#- openjdk8
sudo: required
dist: trusty

services:
- docker

matrix:
  include:
    - jdk: openjdk8
      script: "./gradlew clean checkstyle licenseMain licenseTest --no-daemon"
    - jdk: openjdk8
      env:
        - jdk=java8
        - CI=false
      script: "./gradlew clean assemble --no-daemon -Pjdk=""$jdk"
    - jdk: openjdk11
      env:
        - jdk=java11
        - CI=false
      script: "./gradlew clean assemble --no-daemon -Pjdk=""$jdk"

#env:
#  - CI=false

before_deploy:
- echo build start... sylph
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
