language: java
#jdk:
#- openjdk8
sudo: required


services:
- docker

matrix:
  include:
    - jdk: openjdk8
      script: "./gradlew clean checkstyle licenseMain licenseTest --no-daemon"
      dist: xenial
    - jdk: openjdk8
      script: "./gradlew clean assemble -Pjdk=java8 --no-daemon"
      dist: xenial
    - jdk: openjdk11
      script: "./gradlew clean assemble -Pjdk=java11 --no-daemon"
      dist: focal

env:
  - CI=false

before_deploy:
- echo build start... sylph
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
